[2023-04-04 15:07:58,544] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados manual__2023-04-04T18:07:54.406783+00:00 [queued]>
[2023-04-04 15:07:58,546] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados manual__2023-04-04T18:07:54.406783+00:00 [queued]>
[2023-04-04 15:07:58,548] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-04 15:07:58,548] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-04-04 15:07:58,548] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-04 15:07:58,561] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-04-04 18:07:54.406783+00:00
[2023-04-04 15:07:58,563] {standard_task_runner.py:52} INFO - Started process 7512 to run task
[2023-04-04 15:07:58,565] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'manual__2023-04-04T18:07:54.406783+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpn6gaqz9t', '--error-file', '/tmp/tmp8t0h0aeo']
[2023-04-04 15:07:58,565] {standard_task_runner.py:80} INFO - Job 30: Subtask extrai_dados
[2023-04-04 15:07:58,603] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados manual__2023-04-04T18:07:54.406783+00:00 [running]> on host bruno-H610M-H-DDR4
[2023-04-04 15:07:58,653] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T18:07:54.406783+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-04T18:07:54.406783+00:00
[2023-04-04 15:07:59,615] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/bruno/Documents/airflow_alura/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/bruno/Documents/airflow_alura/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/bruno/Documents/airflow_alura/dags/dados_climaticos.py", line 31, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/bruno/Documents/airflow_alura/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/bruno/Documents/airflow_alura/venv/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/bruno/Documents/airflow_alura/venv/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/bruno/Documents/airflow_alura/venv/lib/python3.10/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/bruno/Documents/airflow_alura/venv/lib/python3.10/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'home/bruno/Documents/airflow_alura/semana=2023-04-04'
[2023-04-04 15:07:59,653] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230404T180754, start_date=20230404T180758, end_date=20230404T180759
[2023-04-04 15:07:59,685] {standard_task_runner.py:92} ERROR - Failed to execute job 30 for task extrai_dados (Cannot save file into a non-existent directory: 'home/bruno/Documents/airflow_alura/semana=2023-04-04'; 7512)
[2023-04-04 15:07:59,700] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-04-04 15:07:59,718] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
